// web/orval.config.ts
export default {
	default: {
		input: {
			target: 'http://localhost:8000/openapi.json'
		},
		output: {
			target: './src/lib/api/gen',
			schemas: './src/lib/api/gen/model',
			mode: 'tags',
			override: {
				header: (info: InfoObject): String[] => [
					`Generated by orval 🍺`,
					`Do not edit manually.`,
					...(info.title ? [info.title] : []),
					...(info.description ? [info.description] : []),
					...(info.version ? [`OpenAPI spec version: ${info.version}`] : [])
				],
				mutator: {
					path: './src/lib/api/axios.ts',
					name: 'axiosInstance'
				}
			}
		}
	}
};

