services:
  db:
    image: postgres:latest
    container_name: fastsvelte-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastsvelte
    ports:
      - "5432:5432"
    volumes:
      - fastsvelte-data:/var/lib/postgresql/data

volumes:
  fastsvelte-data:
    external: true
